#!/bin/sh
# ###########################################################################
# Script generated by HP Fortify SCA Scan Wizard (c) HP Fortify 2011
# Created on 2012/08/23 10:18:03
# ###########################################################################
# Generated for the following languages:
#   HTML
#   Java
#   Javascript
#   JSP J2EE
#   XML
# ###########################################################################
# DEBUG - if set to true, runs SCA in debug mode
# SOURCEANALYZER - the name of the SCA executable
# BUILDID - the SCA build id
# LAUNCHERSWITCHES - the launcher settings that are used to invoke SCA
# ARGFILE - the name of the argument file that's extracted and passed to SCA
# MEMORY - the memory settings for SCA
# CLIENT - the name of the fortifyclient executable
# SSCURL - the SSC url for uploading the FPR
# SSCPROJECT - the name of the project to upload the FPR to
# SSCVERSION - the name of the project version to upload the FPR to
# SSCTOKEN - the token for authenticating the FPR upload
# OLDFILENUMBER - this defines the file which contains the number of files within the project, it is automatically generated
# FILENOMAXDIFF - this is the percentage of difference between the number of files which will trigger a warning by the script
# ###########################################################################

DEBUG=false
SOURCEANALYZER=sourceanalyzer
FPR="webgoat_javajsp.fpr"
SSCURL=http://10.10.10.82:8080/ssc
SSCPROJECT="TEST_Project"
SSCVERSION="JAVA_Project"
SSCTOKEN=3
CLIENT=fortifyclient
BUILDID="WebGoat5.0"
ARGFILE="webgoat_javajsp.sh.args"
MEMORY="-Xmx1024M -Xms600M -Xss24M "

LAUNCHERSWITCHES=""
OLDFILENUMBER=webgoat_javajsp.sh.fileno
FILENOMAXDIFF=10

PROJECTROOT0="/fortify/testsrc/JAVA_JSP/WebGoat5.0"
if [ ! -d "$PROJECTROOT0" ]; then
   echo  "ERROR: This script is being run on a different machine than it was"
   echo  "       generated on or the targeted project has been moved. This script is "
   echo  "       configured to locate files at"
   echo  "          $PROJECTROOT0"
   echo  "       Please modify the \$PROJECTROOT0 variable found"
   echo  "       at the top of this script to point to the corresponding directory"
   echo  "       located on this machine."
   exit
fi

if [ $DEBUG = true ]; then export LAUNCHERSWITCHES="-debug $LAUNCHERSWITCHES"; fi
echo Extracting Arguments File


grep "# ARGS" $0 | grep -v grep | cut -d" " -f3- | sed -e s#PROJECTROOT0_MARKER#"$PROJECTROOT0"#g   > $ARGFILE

# ###########################################################################
echo Cleaning previous scan artifacts
$SOURCEANALYZER $MEMORY $LAUNCHERSWITCHES -b $BUILDID -clean
if [ $? = 1 ] ; then
echo Sourceanalzyer failed, exiting
exit
fi
# ###########################################################################
echo Translating files
$SOURCEANALYZER $MEMORY $LAUNCHERSWITCHES -b $BUILDID @$ARGFILE
if [ $? = 1 ] ; then
echo Sourceanalzyer failed, exiting
exit
fi
# ###########################################################################
echo Testing Difference between Translations
FILENUMBER=`$SOURCEANALYZER -b $BUILDID -show-files | wc -l`

if [ ! -f $OLDFILENUMBER ]; then
  echo It appears to be the first time running this script, setting $OLDFILENUMBER to $FILENUMBER
  echo $FILENUMBER > $OLDFILENUMBER
else
  OLDFILENO=`cat $OLDFILENUMBER`
  DIFF=`expr $OLDFILENO "*" $FILENOMAXDIFF`
  DIFF=`expr $DIFF /  100`

  MAX=`expr $OLDFILENO + $DIFF`
  MIN=`expr $OLDFILENO - $DIFF`

  if [ $FILENUMBER -lt $MIN ] ; then SHOWWARNING=true; fi
  if [ $FILENUMBER -gt $MAX ] ; then SHOWWARNING=true; fi

  if [ $SHOWWARNING == true ] ; then
    echo "WARNING: The number of files has changed by over $FILENOMAXDIFF%, it is recommended"
    echo "         that this script is regenerated with the ScanWizard"
  fi

  echo $MAX $MIN $DIFF
fi;

# ###########################################################################
echo Starting scan
$SOURCEANALYZER $MEMORY $LAUNCHERSWITCHES -b $BUILDID -scan -f $FPR
if [ $? = 1 ] ; then
echo Sourceanalzyer failed, exiting
exit
fi
# ###########################################################################
echo Uploading scan to SSC
$CLIENT -url $SSCURL -authtoken $SSCTOKEN uploadFPR -file $FPR -project $SSCPROJECT -version $SSCVERSION
if [ $? = 1 ] ; then
echo Sourceanalzyer failed, exiting
exit
fi
# ###########################################################################
echo Finished
# ARGS "-cp"
# ARGS "PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/HammerHead.class;PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/lessons/admin/AdminScreen.class;PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/lessons/admin/ProductsAdminScreen.class;PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/lessons/admin/RefreshDBScreen.class;PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/lessons/admin/ReportCardScreen.class"
# ARGS "-cp"
# ARGS "PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/lessons/admin/SummaryReportCardScreen.class;PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/lessons/admin/UserAdminScreen.class;PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/lessons/admin/WelcomeAdminScreen.class;PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/lessons/Category.class;PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/lessons/CrossSiteScripting/EditProfile.class"
# ARGS "-cp"
# ARGS "PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/lessons/CrossSiteScripting/FindProfile.class;PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/lessons/CrossSiteScripting/UpdateProfile.class;PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/lessons/CrossSiteScripting/ViewProfile.class;PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/lessons/DefaultLessonAction.class;PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/lessons/LessonAction.class"
# ARGS "-cp"
# ARGS "PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/lessons/NewLesson.class;PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/lessons/RoleBasedAccessControl/DeleteProfile.class;PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/lessons/RoleBasedAccessControl/EditProfile.class;PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/lessons/RoleBasedAccessControl/FindProfile.class;PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/lessons/RoleBasedAccessControl/ListStaff.class"
# ARGS "-cp"
# ARGS "PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/lessons/RoleBasedAccessControl/Login.class;PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/lessons/RoleBasedAccessControl/Logout.class;PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/lessons/RoleBasedAccessControl/SearchStaff.class;PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/lessons/RoleBasedAccessControl/UpdateProfile.class;PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/lessons/RoleBasedAccessControl/ViewProfile.class"
# ARGS "-cp"
# ARGS "PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/lessons/SQLInjection/ViewProfile.class;PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/lessons/WelcomeScreen.class;PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/LessonSource.class;PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/servlets/Controller.class;PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/session/Authorization.class"
# ARGS "-cp"
# ARGS "PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/session/CreateDB.class;PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/session/DatabaseUtilities.class;PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/session/ECSFactory.class;PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/session/Employee.class;PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/session/EmployeeStub.class"
# ARGS "-cp"
# ARGS "PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/session/ErrorScreen.class;PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/session/LessonSession.class;PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/session/LessonTracker.class;PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/session/Parameter.class;PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/session/ParameterNotFoundException.class"
# ARGS "-cp"
# ARGS "PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/session/ParameterParser.class;PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/session/Screen.class;PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/session/UnauthenticatedException.class;PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/session/UnauthorizedException.class;PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/session/UserTracker.class"
# ARGS "-cp"
# ARGS "PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/session/ValidationException.class;PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/session/WebgoatProperties.class;PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/util/Exec.class;PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/util/ExecResults.class;PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/util/ExecutionException.class"
# ARGS "-cp"
# ARGS "PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/util/HtmlEncoder.class;PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/util/Interceptor.class;PROJECTROOT0_MARKER/build/WEB-INF/classes/org/owasp/webgoat/util/ThreadWatcher.class;PROJECTROOT0_MARKER/tomcat/bin/bootstrap.jar;PROJECTROOT0_MARKER/tomcat/bin/commons-daemon.jar"
# ARGS "-cp"
# ARGS "PROJECTROOT0_MARKER/tomcat/bin/commons-logging-api.jar;PROJECTROOT0_MARKER/tomcat/common/i18n/tomcat-i18n-en.jar;PROJECTROOT0_MARKER/tomcat/common/i18n/tomcat-i18n-es.jar;PROJECTROOT0_MARKER/tomcat/common/i18n/tomcat-i18n-fr.jar;PROJECTROOT0_MARKER/tomcat/common/i18n/tomcat-i18n-ja.jar"
# ARGS "-cp"
# ARGS "PROJECTROOT0_MARKER/tomcat/common/lib/commons-el.jar;PROJECTROOT0_MARKER/tomcat/common/lib/jasper-compiler-jdt.jar;PROJECTROOT0_MARKER/tomcat/common/lib/jasper-compiler.jar;PROJECTROOT0_MARKER/tomcat/common/lib/jasper-runtime.jar;PROJECTROOT0_MARKER/tomcat/common/lib/jsp-api.jar"
# ARGS "-cp"
# ARGS "PROJECTROOT0_MARKER/tomcat/common/lib/naming-factory-dbcp.jar;PROJECTROOT0_MARKER/tomcat/common/lib/naming-factory.jar;PROJECTROOT0_MARKER/tomcat/common/lib/naming-resources.jar;PROJECTROOT0_MARKER/tomcat/common/lib/servlet-api.jar;PROJECTROOT0_MARKER/tomcat/server/lib/catalina-ant.jar"
# ARGS "-cp"
# ARGS "PROJECTROOT0_MARKER/tomcat/server/lib/catalina-cluster.jar;PROJECTROOT0_MARKER/tomcat/server/lib/catalina-optional.jar;PROJECTROOT0_MARKER/tomcat/server/lib/catalina.jar;PROJECTROOT0_MARKER/tomcat/server/lib/commons-modeler.jar;PROJECTROOT0_MARKER/tomcat/server/lib/servlets-default.jar"
# ARGS "-cp"
# ARGS "PROJECTROOT0_MARKER/tomcat/server/lib/servlets-invoker.jar;PROJECTROOT0_MARKER/tomcat/server/lib/servlets-webdav.jar;PROJECTROOT0_MARKER/tomcat/server/lib/tomcat-ajp.jar;PROJECTROOT0_MARKER/tomcat/server/lib/tomcat-coyote.jar;PROJECTROOT0_MARKER/tomcat/server/lib/tomcat-http.jar"
# ARGS "-cp"
# ARGS "PROJECTROOT0_MARKER/tomcat/server/lib/tomcat-util.jar;PROJECTROOT0_MARKER/tomcat/server/webapps/manager/WEB-INF/lib/catalina-manager.jar;PROJECTROOT0_MARKER/tomcat/server/webapps/manager/WEB-INF/lib/commons-fileupload-1.0.jar;PROJECTROOT0_MARKER/tomcat/webapps/balancer/WEB-INF/lib/catalina-balancer.jar;PROJECTROOT0_MARKER/tomcat/webapps/ROOT/WEB-INF/lib/catalina-root.jar"
# ARGS "-cp"
# ARGS "PROJECTROOT0_MARKER/WebContent/WEB-INF/lib/axis-ant.jar;PROJECTROOT0_MARKER/WebContent/WEB-INF/lib/axis.jar;PROJECTROOT0_MARKER/WebContent/WEB-INF/lib/catalina.jar;PROJECTROOT0_MARKER/WebContent/WEB-INF/lib/commons-collections-3.1.jar;PROJECTROOT0_MARKER/WebContent/WEB-INF/lib/commons-digester.jar"
# ARGS "-cp"
# ARGS "PROJECTROOT0_MARKER/WebContent/WEB-INF/lib/commons-discovery-0.2.jar;PROJECTROOT0_MARKER/WebContent/WEB-INF/lib/commons-logging-1.0.4.jar;PROJECTROOT0_MARKER/WebContent/WEB-INF/lib/ecs-1.4.2.jar;PROJECTROOT0_MARKER/WebContent/WEB-INF/lib/idb.jar;PROJECTROOT0_MARKER/WebContent/WEB-INF/lib/j2h.jar"
# ARGS "-cp"
# ARGS "PROJECTROOT0_MARKER/WebContent/WEB-INF/lib/jaxrpc.jar;PROJECTROOT0_MARKER/WebContent/WEB-INF/lib/jta-spec1_0_1.jar;PROJECTROOT0_MARKER/WebContent/WEB-INF/lib/log4j-1.2.8.jar;PROJECTROOT0_MARKER/WebContent/WEB-INF/lib/saaj.jar;PROJECTROOT0_MARKER/WebContent/WEB-INF/lib/wsdl4j-1.5.1.jar"
# ARGS "-source"
# ARGS "1.5"
# ARGS -exclude "PROJECTROOT0_MARKER/**/build.xml"
# ARGS "PROJECTROOT0_MARKER"
